<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNwncmvw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNwncmvw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNwncmvw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNwncmvw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNwncmvw\appProdProjectContainer([
    'container.build_hash' => 'Nwncmvw',
    'container.build_id' => '76936cdb',
    'container.build_time' => 1697452026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNwncmvw');
