<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDzjtvn7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDzjtvn7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDzjtvn7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDzjtvn7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDzjtvn7\appProdProjectContainer([
    'container.build_hash' => 'Dzjtvn7',
    'container.build_id' => '7cafba24',
    'container.build_time' => 1697452163,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDzjtvn7');
